name: CI/CD

on:
  push:
    branches:
      - developer
      - main

jobs:
  run-test:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Run Test
        run: echo "run test!"

  run-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        run: echo "run build!"

  run-deploy:
    if: github.ref == 'refs/heads/main'
    needs: run-build
    runs-on: ubuntu-latest

    steps:
      - name: List Files
        run: ls

      - name: Run Deploy
        run: echo "run deploy!"
